name: Update Calendar

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Dependencies installieren
        run: pip install -r requirements.txt

      - name: Kalender erzeugen
        run: |
          python sfg-fussball-de-home-steingrube.py out.ical
          python sfg-fussball-de-all-matches.py all_matches.ical
          python sfg-fussball-de-all-not-steingrube.py all_not_steingrube.ical

      - name: Änderungen committen
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add out.ical
          git add all_matches.ical
          git add all_not_steingrube.ical
          

          git commit -m "Automatisches Kalenderupdate" || echo "Keine Änderungen"

          git push
